/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.9.4
 *
 */
import { FluencePeer } from '@fluencelabs/fluence';
import type { CallParams$$ } from '@fluencelabs/fluence/dist/internal/compilerSupport/v4'
import {
    callFunction$$,
    registerService$$,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v4';


// Services

export interface DhtDef {
    get_latest_record_by_pk_and_key: (key: string, public_key: string, callParams: CallParams$$<'key' | 'public_key'>) => { cid: string; key: string; name: string; public_key: string; } | Promise<{ cid: string; key: string; name: string; public_key: string; }>;
    get_records_by_key: (key: string, callParams: CallParams$$<'key'>) => { cid: string; key: string; name: string; public_key: string; }[] | Promise<{ cid: string; key: string; name: string; public_key: string; }[]>;
    initialize: (callParams: CallParams$$<null>) => { err_msg: string; success: boolean; } | Promise<{ err_msg: string; success: boolean; }>;
    insert: (key: string, name: string, cid: string, public_key: string, signature: string, message: string, callParams: CallParams$$<'key' | 'name' | 'cid' | 'public_key' | 'signature' | 'message'>) => { err_msg: string; success: boolean; } | Promise<{ err_msg: string; success: boolean; }>;
    shutdown: (callParams: CallParams$$<null>) => { err_msg: string; success: boolean; } | Promise<{ err_msg: string; success: boolean; }>;
}
export function registerDht(serviceId: string, service: DhtDef): void;
export function registerDht(peer: FluencePeer, serviceId: string, service: DhtDef): void;
       

export function registerDht(...args: any) {
    registerService$$(
        args,
        {
    "functions" : {
        "tag" : "labeledProduct",
        "fields" : {
            "get_latest_record_by_pk_and_key" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "key" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "public_key" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "struct",
                            "name" : "FdbDht",
                            "fields" : {
                                "cid" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "key" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "name" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "public_key" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                }
                            }
                        }
                    ]
                }
            },
            "get_records_by_key" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "key" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "array",
                            "type" : {
                                "tag" : "struct",
                                "name" : "FdbDht",
                                "fields" : {
                                    "cid" : {
                                        "tag" : "scalar",
                                        "name" : "string"
                                    },
                                    "key" : {
                                        "tag" : "scalar",
                                        "name" : "string"
                                    },
                                    "name" : {
                                        "tag" : "scalar",
                                        "name" : "string"
                                    },
                                    "public_key" : {
                                        "tag" : "scalar",
                                        "name" : "string"
                                    }
                                }
                            }
                        }
                    ]
                }
            },
            "initialize" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "nil"
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "struct",
                            "name" : "FdbResult",
                            "fields" : {
                                "err_msg" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "success" : {
                                    "tag" : "scalar",
                                    "name" : "bool"
                                }
                            }
                        }
                    ]
                }
            },
            "insert" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "key" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "name" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "cid" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "public_key" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "signature" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "message" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "struct",
                            "name" : "FdbResult",
                            "fields" : {
                                "err_msg" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "success" : {
                                    "tag" : "scalar",
                                    "name" : "bool"
                                }
                            }
                        }
                    ]
                }
            },
            "shutdown" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "nil"
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "struct",
                            "name" : "FdbResult",
                            "fields" : {
                                "err_msg" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "success" : {
                                    "tag" : "scalar",
                                    "name" : "bool"
                                }
                            }
                        }
                    ]
                }
            }
        }
    }
}
    );
}
      
// Functions

