/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.9.4
 *
 */
import { FluencePeer } from '@fluencelabs/fluence';
import type { CallParams$$ } from '@fluencelabs/fluence/dist/internal/compilerSupport/v4'
import {
    callFunction$$,
    registerService$$,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v4';


// Services

// Functions
 

export function add_beat(
    data_key: string,
    token_key: string,
    token_id: string,
    alias: string,
    public_key: string,
    signature: string,
    data: string,
    config?: {ttl?: number}
): Promise<void>;

export function add_beat(
    peer: FluencePeer,
    data_key: string,
    token_key: string,
    token_id: string,
    alias: string,
    public_key: string,
    signature: string,
    data: string,
    config?: {ttl?: number}
): Promise<void>;

export function add_beat(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (seq
                           (seq
                            (seq
                             (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                             (call %init_peer_id% ("getDataSrv" "data_key") [] data_key)
                            )
                            (call %init_peer_id% ("getDataSrv" "token_key") [] token_key)
                           )
                           (call %init_peer_id% ("getDataSrv" "token_id") [] token_id)
                          )
                          (call %init_peer_id% ("getDataSrv" "alias") [] alias)
                         )
                         (call %init_peer_id% ("getDataSrv" "public_key") [] public_key)
                        )
                        (call %init_peer_id% ("getDataSrv" "signature") [] signature)
                       )
                       (call %init_peer_id% ("getDataSrv" "data") [] data)
                      )
                      (xor
                       (call -relay- ("node" "send_transaction") [data_key token_key token_id alias public_key signature data "metadata" 0])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                    )
    `
    return callFunction$$(
        args,
        {
    "functionName" : "add_beat",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                "data_key" : {
                    "tag" : "scalar",
                    "name" : "string"
                },
                "token_key" : {
                    "tag" : "scalar",
                    "name" : "string"
                },
                "token_id" : {
                    "tag" : "scalar",
                    "name" : "string"
                },
                "alias" : {
                    "tag" : "scalar",
                    "name" : "string"
                },
                "public_key" : {
                    "tag" : "scalar",
                    "name" : "string"
                },
                "signature" : {
                    "tag" : "scalar",
                    "name" : "string"
                },
                "data" : {
                    "tag" : "scalar",
                    "name" : "string"
                }
            }
        },
        "codomain" : {
            "tag" : "nil"
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}
